### ISSUE TITLE
 Implementar GET /api/tweets y GET /api/users

### ISSUE THREAD

**Issue by sambrista** [lauraaa96/tweetfony#4]

**Comment by lauraaa96** [comment]
Completado

**Comment by sambrista** [comment]
En /api/tweets las urls que das no funcionan. Eso es porque has generado URLs para la ruta ``api_get_tweets`` (la que devuelve la lista de tweets), cuando debería ser ``api_get_tweet`` (la que devuelve los detalles de un tweet).

**Comment by lauraaa96** [comment]
Vale, ya está corregido

**Comment by sambrista** [comment]
Comprobado
